genesis:
  chain_id: "step_108101-1"
  app_state:
    staking:
      params:
        bond_denom: "tenet"
        unbonding_time: "1296000s"
        max_validators: 64
    crisis:
      constant_fee:
        denom: "tenet"
    gov:
      deposit_params:
        min_deposit:
          - denom: "tenet"
            amount: "1000000000000000000"
accounts:
  - name: myacc
    coins:
      - 100000000tenet
validators:
  - name: alice
    bonded: 1000000tenet
    config:
      instrumentation:
        prometheus: true
  - name: bob
    bonded: 1000000tenet